name: Keep Streamlit Awake

on:
  schedule:
    # 20분마다 실행 (30분 규칙을 피하기 위함)
    - cron: '*/20 * * * *'
  workflow_dispatch: # 수동 실행 버튼

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Poke Streamlit
        run: |
          curl -I https://stock-alarm-nwgxkui9krfqw6xddswa6n.streamlit.app/