name: Stock Alarm Daily

on:
  schedule:
    - cron: '10 21 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v3 -> v4 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5 # v4 -> v5 업데이트
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MY_GIST_ID: ${{ secrets.MY_GIST_ID }}
          MY_TELEGRAM_TOKEN: ${{ secrets.MY_TELEGRAM_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
          # Node.js 24 강제 설정 추가
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: python main.py
