name: Stock Alarm Daily

on:
  schedule:
    # 1. 새벽 기상 보고 & 안티슬립 (03:00 KST / UTC 18:00)
    - cron: '0 18 * * *'
    # 2. 메인 주식 알람 (화~토 06:10 KST / UTC 월~금 21:10)
    - cron: '10 21 * * 1-5'
    # 3. 오후 현황 보고 & 안티슬립 (15:00 KST / UTC 06:00)
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          MY_GIST_ID: ${{ secrets.MY_GIST_ID }}
          MY_TELEGRAM_TOKEN: ${{ secrets.MY_TELEGRAM_TOKEN }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        run: python main.py
